name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Minds.SDK/Minds.SDK.csproj

      - name: Build project
        run: dotnet build Minds.SDK/Minds.SDK.csproj --configuration Release

      - name: Publish project
        run: dotnet publish Minds.SDK/Minds.SDK.csproj -c Release -o output

      - name: Create ZIP of output
        run: zip -r Minds-${{github.ref_name}}.zip output/*  # Create a ZIP file of the output directory

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # This uses the tag that triggered the workflow
          name: Minds.SDK ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            output/*
            Minds-${{github.ref_name}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

